Transactions back
MantasGra/Financify pull request #14
Opened 2020-05-30 23:50 UTC by RenatasB

2020-05-31 00:42 UTC, MartynasKasp requested changes

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/containers/accounts/eliminationForm/index.tsx
> +    newValue: number |'';
uztenka number, nereikia `| ''`

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/containers/accounts/eliminationForm/index.tsx
> +    newValue: '',
jei ce number, tai tada `newValue: 0` ir visur kai tikrini ar formoj pateiktas newValue, tai tikrini ar nelygu 0

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/containers/accounts/eliminationForm/style.module.scss
> +.text {
nenaudojama klase

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/containers/accounts/eliminationForm/style.module.scss
> +.button {
nenaudojama klase

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/store/modules/accounts/actions.ts
> +  | ReturnType<typeof clearEliminationFormErrors>
kabliataskio gale

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/store/modules/accounts/sagas.ts
> +        text: 'Your account balance is already the number you entered.',
kas?

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/store/modules/accounts/sagas.ts
> +        text: 'Your account balance is already the number you entered.',
ir 200 status reiskia OK, kodel rodai info message

2020-05-31 00:42 UTC, MartynasKasp commented on client/src/utils/routes.ts
> +  EliminateMismatch = '/accounts/eliminatemismatch'
use kebab case for route

2020-05-31 00:42 UTC, MartynasKasp commented on server/server/Controllers/TransactionController.cs
> +            return CreatedAtAction(nameof(GetTransactions), new { Id = tmp.Id }, _transactionManager.GetTransaction(tmp.Id, _transactionIncludes));
tau nereikia kreiptis i transaction manageri, uztenka kreiptis i controllerio get metoda

2020-06-01 14:19 UTC, RenatasB commented on server/server/Controllers/TransactionController.cs
> +            return CreatedAtAction(nameof(GetTransactions), new { Id = tmp.Id }, _transactionManager.GetTransaction(tmp.Id, _transactionIncludes));
no

2020-06-01 14:20 UTC, RenatasB commented on client/src/containers/accounts/eliminationForm/style.module.scss
> +.button {
naudojama

2020-06-01 14:21 UTC, RenatasB commented on client/src/containers/accounts/eliminationForm/style.module.scss
> +.text {
naudojama

2020-06-01 14:21 UTC, RenatasB commented on client/src/containers/accounts/eliminationForm/index.tsx
> +    newValue: '',
no

2020-06-01 14:21 UTC, RenatasB commented on client/src/containers/accounts/eliminationForm/index.tsx
> +    newValue: number |'';
no

2020-06-01 20:15 UTC, MartynasKasp approved these changes

2020-06-01 20:16 UTC, MartynasKasp commented
norejau kazka irodyt bet dabar as bbd

2020-06-01 21:03 UTC, merged