Entities
MantasGra/Financify pull request #2
Opened 2020-04-14 15:49 UTC by MartynasKasp

2020-04-14 15:56 UTC, MantasGra reviewed
Looks good, reiktų kad Mykolas arba Povilas pažiūrėtų tho

2020-04-14 15:56 UTC, MantasGra commented on server/server/Models/BugReport.cs
> +        public string Contnet { get; set; }
nice variable name

2020-04-14 16:01 UTC, MartynasKasp commented on server/server/Models/BugReport.cs
> +        public string Contnet { get; set; }
fixed

2020-04-14 17:46 UTC, pockeviciuspovilas requested changes
Need annotations [Required] to fix non-nullable types, also use annotations like [Column(TypeName = "varchar(xxx)")] to optimize DB a bit.

2020-04-14 21:49 UTC, MartynasKasp reviewed
Changes were made

2020-04-14 22:01 UTC, MantasGra approved these changes
Solid work

2020-04-15 10:06 UTC, pockeviciuspovilas approved these changes
Looks good, well done

2020-04-15 10:30 UTC, merged