Front accounts
MantasGra/Financify pull request #3
Opened 2020-04-25 22:40 UTC by MykolasVitkus

2020-04-25 22:41 UTC, MykolasVitkus commented on client/src/components/snackbar/index.tsx
> +        autoHideDuration={6000}
cia dar galima idet i SnackbarType durationa, bet uztingejau

2020-04-26 14:43 UTC, MartynasKasp commented on client/src/components/snackbar/index.tsx
> +        autoHideDuration={6000}
tai įdėk jei galima

2020-04-26 15:00 UTC, MantasGra requested changes
šiaip visai good, reikia code quality improvint

2020-04-26 15:00 UTC, MantasGra commented on client/src/components/snackbar/index.tsx
> +  root: {
Būtų gerai outsourcint styles visada į css/scss, jei įmanoma.

2020-04-26 15:00 UTC, MantasGra commented on client/src/components/snackbar/index.tsx
> +        autoHideDuration={6000}
gera idėja, do it

2020-04-26 15:00 UTC, MantasGra commented on client/src/containers/accounts/form/style.module.scss
> +  font-size: 40px;
kaip matau yra unused styles šitam faile

2020-04-26 15:00 UTC, MantasGra commented on client/src/containers/accounts/list/index.tsx
> +  }, []);
čia turėtų būt dependency [dispatch]

2020-04-26 15:00 UTC, MantasGra commented on client/src/containers/accounts/list/index.tsx
> +                        <DeleteIcon style={{ color: 'red' }} />
būtų gerai inline styles nenaudot

2020-04-26 15:00 UTC, MantasGra commented on client/src/containers/example/index.tsx
> +            Press button below to pop out a random fact!
good change

2020-04-26 15:00 UTC, MantasGra commented on client/src/containers/accounts/list/index.tsx
> +  // Select the random fact from redux state.
I don't think this comment applies here

2020-04-26 15:00 UTC, MantasGra commented on client/src/store/actions.ts
> +export const createAction = <T extends any>(type: any) => (
oof, kas čia nutiko? nereikia taip daryti.

2020-04-26 15:00 UTC, MantasGra commented on client/src/store/modules/accounts/actions.ts
> +  | ReturnType<typeof setAccounts>;
trūksta setModalOpen

2020-04-26 15:00 UTC, MantasGra commented on client/src/containers/accounts/list/style.module.scss
> +  padding: 5px;
gali būti, kad čia unused styles yra

2020-04-26 15:00 UTC, MantasGra commented on client/src/store/modules/accounts/requests.ts
> +      type: string;
čia blogas type

2020-04-26 15:00 UTC, MantasGra commented on client/src/store/modules/accounts/types.ts
> +export type AccountActionNameType = typeof GET_ACCOUNTS | typeof SET_ACCOUNTS;
trūksta set modal

2020-04-26 15:00 UTC, MantasGra commented on client/src/store/types.ts
> +
čia neturėtų šito būt, rekėjo viršutinį type extendint, tada nebūtų reikėję action creatoriuje į any pakeist

2020-04-26 15:40 UTC, MartynasKasp commented
Kodėl nesujungei su backu? Neveikia tik patchas, visa kita veikia, tai gali ir sujungt iškart, kad po to nebereikėtų grįžti.

2020-04-27 08:59 UTC, MykolasVitkus commented on client/src/components/snackbar/index.tsx
> +        autoHideDuration={6000}
nenoriu

2020-04-27 15:01 UTC, MartynasKasp commented
asd

2020-05-11 19:02 UTC, MantasGra approved these changes
Good

2020-05-11 19:02 UTC, merged